import { describe, it, expect, afterEach } from 'vitest';
import { mkdtemp, readFile, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { openProject } from '@rmmz-kit/core';
import * as tools from '../src/tools.js';
import { formatPluginsJs, parsePluginsJs } from '../src/plugins.js';
import { assetCatalog } from '../src/resources.js';
import { makeTestProject } from './testProject.js';

/** A file to import: contents don't matter, only that the bytes survive the copy. */
async function sourceFile(name: string, bytes = [0x89, 0x50, 0x4e, 0x47]): Promise<string> {
  const dir = await mkdtemp(path.join(tmpdir(), 'rmmz-asset-'));
  const file = path.join(dir, name);
  await writeFile(file, Buffer.from(bytes));
  return file;
}

describe('manage_plugins (M7.6)', () => {
  const cleanups: Array<() => Promise<void>> = [];
  afterEach(async () => {
    await Promise.all(cleanups.splice(0).map((fn) => fn()));
  });

  it('reads the fixture list without touching it', async () => {
    const { dir, cleanup } = await makeTestProject();
    cleanups.push(cleanup);
    const session = await openProject(dir);

    expect(await tools.managePlugins(session)).toEqual([
      { name: 'TestPlugin', status: true, description: 'Test Plugin', parameters: {} },
    ]);
    expect(session.rawWriteFiles()).toEqual([]);
  });

  it('merges a patch by name and leaves the rest of the entry alone', async () => {
    const { dir, cleanup } = await makeTestProject();
    cleanups.push(cleanup);
    const session = await openProject(dir);

    const plugins = await tools.managePlugins(session, [{ name: 'TestPlugin', status: false, parameters: { speed: '3' } }]);
    expect(plugins).toEqual([
      { name: 'TestPlugin', status: false, description: 'Test Plugin', parameters: { speed: '3' } },
    ]);

    await session.commit('chore: disable TestPlugin');
    const written = await readFile(path.join(dir, 'js', 'plugins.js'), 'utf-8');
    expect(parsePluginsJs(written).entries[0]).toEqual(plugins[0]);
    // The header the project shipped with survives the rewrite.
    expect(written.startsWith('// Generated by RPG Maker.')).toBe(true);
  });

  it('refuses to list a plugin whose js file is not there', async () => {
    const { dir, cleanup } = await makeTestProject();
    cleanups.push(cleanup);
    const session = await openProject(dir);

    // The name is a filename an agent typed from memory, and MZ turns a missing
    // one into a crash on boot rather than a warning.
    await expect(tools.managePlugins(session, [{ name: 'TestPlugn' }])).rejects.toThrow(/No such plugin/);
    expect(session.rawWriteFiles()).toEqual([]);
  });

  it('rejects a plugins.js it cannot parse instead of overwriting it', async () => {
    const { dir, cleanup } = await makeTestProject();
    cleanups.push(cleanup);
    const session = await openProject(dir);
    await writeFile(path.join(dir, 'js', 'plugins.js'), 'var $plugins =\n[\n{name: "Loose"},\n];\n');

    await expect(tools.managePlugins(session)).rejects.toThrow(/cannot parse/);
  });

  it('round-trips through format/parse', () => {
    const entries = [
      { name: 'A', status: true, description: 'first', parameters: { x: '1' } },
      { name: 'B', status: false, description: '', parameters: {} },
    ];
    expect(parsePluginsJs(formatPluginsJs(entries)).entries).toEqual(entries);
  });
});

describe('import_asset (M7.6)', () => {
  const cleanups: Array<() => Promise<void>> = [];
  afterEach(async () => {
    await Promise.all(cleanups.splice(0).map((fn) => fn()));
  });

  it('copies a file into the right folder on commit, and shows it in the catalog before that', async () => {
    const { dir, cleanup } = await makeTestProject();
    cleanups.push(cleanup);
    const session = await openProject(dir);

    const result = await tools.importAsset(session, { dir: 'img/characters', source: await sourceFile('Hero.png') });
    expect(result).toEqual({ path: 'img/characters/Hero.png' });

    // Uncommitted, but a model asking "what characters exist?" is about to
    // reference it — the catalog would otherwise talk it out of its own import.
    expect((await assetCatalog(session))['img/characters']).toEqual(['Hero']);

    await session.commit('feat: import Hero');
    expect([...(await readFile(path.join(dir, 'img', 'characters', 'Hero.png')))]).toEqual([0x89, 0x50, 0x4e, 0x47]);
  });

  it('renames on import when asked', async () => {
    const { dir, cleanup } = await makeTestProject();
    cleanups.push(cleanup);
    const session = await openProject(dir);

    const result = await tools.importAsset(session, {
      dir: 'audio/se',
      source: await sourceFile('door_open_final_v2.ogg'),
      name: 'DoorOpen.ogg',
    });
    expect(result.path).toBe('audio/se/DoorOpen.ogg');
  });

  it('imports a plugin file into js/plugins and can enable it in the same session', async () => {
    const { dir, cleanup } = await makeTestProject();
    cleanups.push(cleanup);
    const session = await openProject(dir);

    // The whole point: import_asset stages the file, readRaw sees staged
    // writes, so manage_plugins' "No such plugin" guard passes before commit —
    // one session covers install-and-enable instead of dead-ending at
    // "copy the file in by hand".
    const source = await sourceFile('BattleVoiceMZ.js', [...Buffer.from('// battle voice plugin\n')]);
    const result = await tools.importAsset(session, { dir: 'js/plugins', source });
    expect(result).toEqual({ path: 'js/plugins/BattleVoiceMZ.js' });

    // The catalog grounds manage_plugins names the same way it grounds sprites.
    expect((await assetCatalog(session))['js/plugins']).toEqual(['BattleVoiceMZ', 'TestPlugin']);

    const plugins = await tools.managePlugins(session, [{ name: 'BattleVoiceMZ', parameters: { volume: '90' } }]);
    expect(plugins.find((entry) => entry.name === 'BattleVoiceMZ')).toEqual({
      name: 'BattleVoiceMZ',
      status: true,
      description: '',
      parameters: { volume: '90' },
    });

    await session.commit('feat: install BattleVoiceMZ');
    expect(await readFile(path.join(dir, 'js', 'plugins', 'BattleVoiceMZ.js'), 'utf-8')).toBe('// battle voice plugin\n');
    const written = await readFile(path.join(dir, 'js', 'plugins.js'), 'utf-8');
    expect(parsePluginsJs(written).entries.map((entry) => entry.name)).toContain('BattleVoiceMZ');
  });

  it('rejects a non-js file aimed at js/plugins', async () => {
    const { dir, cleanup } = await makeTestProject();
    cleanups.push(cleanup);
    const session = await openProject(dir);
    const source = await sourceFile('Hero.png');

    // PluginManager.loadScript appends .js, so anything else never loads.
    await expect(tools.importAsset(session, { dir: 'js/plugins', source })).rejects.toThrow(/takes .js/);
  });

  it('rejects an unknown folder, a wrong extension, and a name with a path in it', async () => {
    const { dir, cleanup } = await makeTestProject();
    cleanups.push(cleanup);
    const session = await openProject(dir);
    const source = await sourceFile('Hero.png');

    await expect(tools.importAsset(session, { dir: 'img/heroes', source })).rejects.toThrow(/Unknown asset folder/);
    // MZ appends the extension itself, so a .jpg character sheet simply never loads.
    await expect(tools.importAsset(session, { dir: 'img/characters', source, name: 'Hero.jpg' })).rejects.toThrow(/takes .png/);
    await expect(tools.importAsset(session, { dir: 'audio/se', source, name: 'Beep.ogg' })).resolves.toBeTruthy();
    await expect(tools.importAsset(session, { dir: 'img/characters', source, name: '../../Hero.png' })).rejects.toThrow(
      /plain filename/
    );
    await expect(tools.importAsset(session, { dir: 'img/characters', source: path.join(dir, 'nope.png') })).rejects.toThrow(
      /Cannot read/
    );
  });
});
