/**
 * js/plugins.js is a JavaScript file, not data: `var $plugins = [ ... ];`, with
 * one JSON object per plugin. Every assumption about that shape lives here, the
 * same way core's io/format.ts isolates the data/*.json one (risk R1) — the
 * editor regenerates this file and nobody has documented the format, so a
 * correction should be a one-file change.
 *
 * Reading is deliberately JSON.parse over the array literal rather than a JS
 * parser: the editor writes strict JSON entries, and a file hand-edited into
 * something JSON.parse rejects is a file we should refuse to rewrite anyway —
 * the header says so in as many words.
 */

export interface PluginEntry {
  /** The plugin's js filename without `.js`, i.e. js/plugins/<name>.js. */
  name: string;
  status: boolean;
  description: string;
  parameters: Record<string, unknown>;
}

export const PLUGINS_FILE = 'js/plugins.js';

const DEFAULT_HEADER = '//=============================================================================\n// Generated by RPG Maker.\n// Do not edit this file directly.\n//=============================================================================\n\n';

/** Everything before `var $plugins` is preserved verbatim on rewrite: a project may carry its own banner, and losing it is a diff nobody asked for. */
export function parsePluginsJs(text: string): { header: string; entries: PluginEntry[] } {
  const match = /^([\s\S]*?)var\s+\$plugins\s*=\s*(\[[\s\S]*\])\s*;?\s*$/.exec(text);
  if (!match) {
    throw new Error(`${PLUGINS_FILE} does not look like an RPG Maker plugin list (no \`var $plugins = [...]\`)`);
  }
  let entries: unknown;
  try {
    entries = JSON.parse(match[2]);
  } catch (err) {
    throw new Error(`${PLUGINS_FILE} has a plugin list this tool cannot parse (hand-edited?): ${(err as Error).message}`);
  }
  if (!Array.isArray(entries)) throw new Error(`${PLUGINS_FILE}'s $plugins is not an array`);
  return { header: match[1], entries: entries as PluginEntry[] };
}

/** One entry per line, compact — what the editor writes, and what keeps a plugin toggle a one-line diff. */
export function formatPluginsJs(entries: PluginEntry[], header = DEFAULT_HEADER): string {
  return `${header}var $plugins =\n[\n${entries.map((entry) => JSON.stringify(entry)).join(',\n')}\n];\n`;
}
